In [2]:
import numpy as np
import pandas as pd

# **Numpy Questions**

**Task#1**

In [3]:
matrix = np.random.randint(1, 100, (4, 4))
print(matrix)
matrix[matrix % 2 != 0] = -1
print(matrix)

[[ 9 33 16 92]
 [25 27  8 58]
 [51 78 26 87]
 [19 59 11 10]]
[[-1 -1 16 92]
 [-1 -1  8 58]
 [-1 78 26 -1]
 [-1 -1 -1 10]]


**Task#2**

In [4]:
arr = np.random.randint(1, 100, (15))
print(arr)
print("Index of Maximun in Array:", np.where(arr == np.max(arr)))
print("Index of Minimun in Array:", np.where(arr == np.min(arr)))

[ 4  2 25 79 54 67 56  8 82 97 43 43 13 55 26]
Index of Maximun in Array: (array([9]),)
Index of Minimun in Array: (array([1]),)


**Task#3**

In [5]:
matrix = np.random.randint(1, 100, (3, 3))
print(matrix)
print("Row-wise Sum:", np.sum(matrix, axis=1))
print("Column-wise Sum:", np.sum(matrix, axis=0))

[[31 45 41]
 [16 11 17]
 [22 19 45]]
Row-wise Sum: [117  44  86]
Column-wise Sum: [ 69  75 103]


**Task#4**

In [6]:
matrix = np.random.rand(5, 5)
print(matrix)
min_value = 0
max_value = 1
normalized_matrix = (matrix - min_value) / (max_value - min_value)
print(normalized_matrix)

[[0.88408594 0.6229909  0.85570182 0.0152436  0.15932938]
 [0.00994862 0.2717246  0.47061622 0.01189838 0.22396792]
 [0.67803029 0.59188773 0.25838579 0.34662213 0.91164797]
 [0.21371067 0.91408315 0.7749757  0.48936936 0.27057203]
 [0.80342391 0.78139336 0.90135351 0.93673791 0.74913795]]
[[0.88408594 0.6229909  0.85570182 0.0152436  0.15932938]
 [0.00994862 0.2717246  0.47061622 0.01189838 0.22396792]
 [0.67803029 0.59188773 0.25838579 0.34662213 0.91164797]
 [0.21371067 0.91408315 0.7749757  0.48936936 0.27057203]
 [0.80342391 0.78139336 0.90135351 0.93673791 0.74913795]]


**Task#5**

In [7]:
arr1 = np.random.randint(1, 100, 5)
arr2 = np.random.randint(1, 100, 5)
print(arr1)
print(arr2)
print("Dot Product:", np.dot(arr1, arr2))

[58  5  8 35 82]
[37 57 62 86 67]
Dot Product: 11431


**Task#6**

In [8]:
arr = np.random.randint(1, 100, (5, 5))
print(arr)
arr.sort(axis=1)
print(arr)

[[67 11 79 30 52]
 [32 11 37 98  7]
 [52 12 72 92 44]
 [85 55 39 40 35]
 [28 86 35 14 42]]
[[11 30 52 67 79]
 [ 7 11 32 37 98]
 [12 44 52 72 92]
 [35 39 40 55 85]
 [14 28 35 42 86]]


**Task#7**

In [ ]:
matrix = np.random.randint(1, 100, (5, 5))
print(matrix)
print("Sum of Diagonal Elements:", np.trace(matrix))

# **Pandas Questions**

**Task#1**

In [9]:
df = pd.DataFrame({'Date': ['2024-02-02', '2024-03-02', '2024-04-01', '2024-05-02'],
                   'Product': ['A', 'B', 'C', 'D'],
                   'Sales': [300, 240, 110, 190]})

product_sales = df.groupby('Product')['Sales'].sum()
print(product_sales)

Product
A    300
B    240
C    110
D    190
Name: Sales, dtype: int64


**Task#2**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size=(10, 4)), columns=list('ABCD'))
print(df)
print(df[df['A'] > 50])

    A   B   C   D
0   9  58   9  33
1  68  40  80  67
2  84   4  83  85
3  76  82  71  74
4  46  59  25  84
5  80  17  42  43
6  64   3  20  27
7  33  80  25  47
8  79   2  90  69
9   1  14  98  11
    A   B   C   D
1  68  40  80  67
2  84   4  83  85
3  76  82  71  74
5  80  17  42  43
6  64   3  20  27
8  79   2  90  69


**Task#3**

In [ ]:
data = {'Name': ['Ahmed', 'Taha', 'Ali', 'Ahmed'],
        'Age': [26, 24, 29, 25],
        'Salary': [55000, 67000, 65000, 79000],
        'Bonus': [4000, 5000, 7000, 6000]}

df = pd.DataFrame(data)
df['Total Compensation'] = df['Salary'] + df['Bonus']
print(df)

    Name  Age  Salary  Bonus  Total Compensation
0  Ahmed   26   55000   4000               59000
1   Taha   24   67000   5000               72000
2    Ali   29   65000   7000               72000
3  Ahmed   25   79000   6000               85000


**Task#4**

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'Age': [25, 30, np.nan, 28, np.nan],
        'Salary': [60000, np.nan, 80000, 75000, np.nan],
        'Bonus': [np.nan, 5000, np.nan, 4000, np.nan]}

print(df)
df = pd.DataFrame(data)
df = df.dropna()
print(df)

    Name   Age   Salary   Bonus
3  David  28.0  75000.0  4000.0
    Name   Age   Salary   Bonus
3  David  28.0  75000.0  4000.0


**Task#5**

In [ ]:
data = {'Year': ['2001', '2002', '2003', '2004', '2004'],
        'Revenue': [250000, 300000, 400000, 350000, 220000],
        'Profit': [60000, 68000, 80000, 75000, 71000],
        }

df = pd.DataFrame(data)
print(df)
print(df[df['Profit'] < 0])

   Year  Revenue  Profit
0  2001   250000   60000
1  2002   300000   68000
2  2003   400000   80000
3  2004   350000   75000
4  2004   220000   71000
Empty DataFrame
Columns: [Year, Revenue, Profit]
Index: []


**Task#6**

In [10]:
data = {'Date': pd.date_range(start='2023-01-01', end='2023-01-10'),
        'Value': np.random.randint(10, 100, 10)}
df = pd.DataFrame(data)

df['Previous Day Value'] = df['Value'].shift(periods=1)

print(df)

        Date  Value  Previous Day Value
0 2023-01-01     50                 NaN
1 2023-01-02     34                50.0
2 2023-01-03     57                34.0
3 2023-01-04     26                57.0
4 2023-01-05     40                26.0
5 2023-01-06     55                40.0
6 2023-01-07     13                55.0
7 2023-01-08     36                13.0
8 2023-01-09     12                36.0
9 2023-01-10     58                12.0


**Task#7**

In [11]:
data = {'Product': ['Apple', 'Bag', 'Airplane', 'Boat'],
        'Price': [120, 80, 150, 70],
        'Discount': [0, 0, 0, 0]}
df = pd.DataFrame(data)

df.loc[df['Price'] > 100, 'Price'] = df['Price'] * 0.9
df.loc[df['Price'] > 100, 'Discount'] = 10

print(df)

    Product  Price  Discount
0     Apple    108        10
1       Bag     80         0
2  Airplane    135        10
3      Boat     70         0
